### ISSUE TITLE
Page scrolling

### ISSUE THREAD

**Issue by adam1lake** [feds01/durak-cards#39]
Page has both vertical and horizontal scroll bars. There is blank space when scrolling to the right.[
![issue](https://user-images.githubusercontent.com/54553845/107130860-986e1b00-68c9-11eb-9bd3-b79cbb1f5a80.PNG)
](url)

**Comment by feds01** [comment]
fixed issue https://github.com/feds01/durak-cards-client/commit/1fdbaec87bef11d2ddd617d71dbce156aae2a2f9
